export const MOCK_MENU=[
    {
        id:58,
        label:'职称类',
        level:1,
        code:'2001',
        sort:1,
        children:[
            {
                id:61,
                label:'工程系列',
                level:2,
                sort:1,
                code:'2001001',
                children:[
                    {
                        id:64,
                        label:'院本级或场所评审会',
                        level:3,
                        sort:1,
                        code:'2001001001',  
                        categoryCode:'1001',
                        children:[
                            {
                                id:67,
                                label:'正高级评审',
                                level:4,
                                sort:1,
                                code:'2001001001001',  
                            },
                            {
                                id:68,
                                label:'正高级转系列',
                                level:4,
                                sort:2,
                                code:'2001001001002',  
                            },
                            {
                                id:69,
                                label:'副高级评审',
                                level:4,
                                sort:3,
                                code:'2001001001003',  
                            },
                            {
                                id:70,
                                label:'副高级转系列',
                                level:4,
                                sort:4,
                                code:'2001001001004',  
                            },
                            {
                                id:71,
                                label:'中级认定',
                                level:4,
                                sort:6,
                                code:'2001001001005',  
                            },
                            {
                                id:74,
                                label:'初级认定',
                                level:4,
                                sort:8,
                                code:'2001001001003',  
                            },
                            {
                                id:76,
                                label:'员级认定',
                                level:4,
                                sort:10,
                                code:'2001001001003',  
                            },

                        ],
                    },
                ],
            },
            {
                id:61,
                label:'测试系列',
                level:2,
                sort:1,
                code:'2001001',
                children:[
                    {
                        id:64,
                        label:'test',
                        level:3,
                        sort:1,
                        code:'2001001001',  
                        // categoryCode:'1001',
                        children:[
                            {
                                id:67,
                                label:'正高级评审',
                                level:4,
                                sort:1,
                                code:'2001001001001',  
                            },
                            {
                                id:68,
                                label:'正高级转系列',
                                level:4,
                                sort:2,
                                code:'2001001001002',  
                            },
                            {
                                id:69,
                                label:'副高级评审',
                                level:4,
                                sort:3,
                                code:'2001001001003',  
                            },
                            {
                                id:70,
                                label:'副高级转系列',
                                level:4,
                                sort:4,
                                code:'2001001001004',  
                            },
                            {
                                id:71,
                                label:'中级认定',
                                level:4,
                                sort:6,
                                code:'2001001001005',  
                            },
                            {
                                id:74,
                                label:'初级认定',
                                level:4,
                                sort:8,
                                code:'2001001001003',  
                            },
                            {
                                id:76,
                                label:'员级认定',
                                level:4,
                                sort:10,
                                code:'2001001001003',  
                            },

                        ],
                    },
                ],
            },

        ]
    },
    {
        categoryCode:'111',
        label:'技能类',
        level:1,
    },
    {
        categoryCode:'111',
        label:'专家类',
        level:1,
    },

]


export const MOCK_ENUMS=[
    {
        label:'单位',
        code:'1001',
        dictionaries:[
            {label:'院本级',code:'1001001'},
            {label:'中国火箭',code:'1001002'}
        ]
    },
    {
        label:'专业组',
        code:'1002',
        dictionaries:[
            {label:'军品技术总体组',code:'1001001'},
            {label:'军品技术系统组',code:'1001001'},
        ]
    }
]